name: "Exercicio2 06022023"

on: [push]
  
jobs:
  
    cria_e_upload_artefato:
      name: "Cria o artefato e faz o upload"
      runs-on: ubuntu-latest
      
      steps:
      
        - name: Checkout repositpry
          uses: actions/checkout@v3.3.0
          
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            name: ${{ vars.VARIABLE_NALON }}
            path: .
            retention-days: 15
